### ISSUE TITLE
Problems in Windows

### ISSUE THREAD

**Issue by AnshulHardat** [ozzai/wizard#1]
I face two problems with running this on windows 10:
It throws the following on wiz train:
`Traceback (most recent call last):
  File "c:\users\zack\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\zack\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Zack\Anaconda3\Scripts\wiz.exe\__main__.py", line 9, in <module>
  File "c:\users\zack\anaconda3\lib\site-packages\flask_wizard_cli\command_line.py", line 25, in main
    learn(arguments)
  File "c:\users\zack\anaconda3\lib\site-packages\flask_wizard_cli\command_line.py", line 118, in learn
    training_data = load_data(os.path.join(path, 'train.json'), 'en')
  File "c:\users\zack\anaconda3\lib\site-packages\rasa_nlu\converters.py", line 268, in load_data
    raise ValueError("unknown training file format : {} for file {}".format(fformat, resource_name))
ValueError: unknown training file format : en for file c:\Webs\pythonZ\wizard\train\train.json`
and with wiz run:
`Traceback (most recent call last):
  File "c:\users\zack\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\zack\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Zack\Anaconda3\Scripts\wiz.exe\__main__.py", line 9, in <module>
  File "c:\users\zack\anaconda3\lib\site-packages\flask_wizard_cli\command_line.py", line 31, in main
    run(arguments)
  File "c:\users\zack\anaconda3\lib\site-packages\flask_wizard_cli\command_line.py", line 225, in run
    call(["python3","main.py"])
  File "c:\users\zack\anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\zack\anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\users\zack\anaconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by AnshulHardat** [comment]
It seems to become unformatted in github, sharing with pastebin:
wiz train ~ https://pastebin.com/raw/f96crqSs
wiz run ~ https://pastebin.com/raw/Jfmf27wE

**Comment by GanadiniAkshay** [comment]
Fixed windows running error with commit [#dc549f6 ](https://github.com/ozzai/wizard/commit/dc549f64021a67ec5059b6af3d9d141df148f60d)

But discovered a new issue Mitie doesn't build on windows and this seems to be an issue on mitie..looking at workarounds

**Comment by GanadiniAkshay** [comment]
okay spacy_sklearn can't do entity recognition and installing mitie is incredibly hard.
So for now we will say rasa is not supported on windows and they can use api.ai or wit.ai
